apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eypa3lp0q-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:ff9c8ebcd0de21fe07026d6718924fef25dbaea7@sha256:9f639a694fc82d45c2ff4e1804de7a2e6e7b2e644e332eb199e223a54bdd3bcc
          name: container-image
