apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eypa3lp0q-python
  janus-idp.io/tekton: eypa3lp0q-python
  backstage.io/kubernetes-id: eypa3lp0q-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eypa3lp0q-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
